# Generated by Django 3.2.12 on 2022-03-27 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTrucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type_name', models.CharField(blank=True, max_length=254)),
                ('truck_number', models.BigIntegerField(blank=True)),
                ('trailer_number', models.BigIntegerField(blank=True)),
                ('refeer', models.CharField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Truck type',
                'verbose_name_plural': 'Truck types',
            },
        ),
        migrations.RemoveField(
            model_name='trucktype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='drivernotes',
            name='noted_by',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='truck_info',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='truck_type',
        ),
        migrations.RemoveField(
            model_name='trailerstogo',
            name='place',
        ),
        migrations.AddField(
            model_name='drivers',
            name='birthdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailerstogo',
            name='emptyplace',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.DeleteModel(
            name='TruckInfo',
        ),
        migrations.DeleteModel(
            name='TruckType',
        ),
        migrations.AddField(
            model_name='drivertrucks',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivers'),
        ),
    ]
