# Generated by Django 3.2.12 on 2022-03-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20220327_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivernotes',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_on_driver', to='drivers.drivers'),
        ),
        migrations.AlterField(
            model_name='drivertrucks',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='truck_owner', to='drivers.drivers'),
        ),
        migrations.AlterField(
            model_name='trailerstogo',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers_to_go', to='drivers.drivers'),
        ),
    ]
