# Generated by Django 3.2.12 on 2022-03-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20220327_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertrucks',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='truck_owners', to='drivers.drivers'),
        ),
    ]
