# Generated by Django 3.2.12 on 2022-03-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_drivertrucks_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertrucks',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_owner', to='drivers.drivers'),
        ),
    ]
